import React, { useState } from 'react';
import axios from 'axios';
import { Activity, AlertCircle, Droplet, CheckCircle2, Download } from 'lucide-react';

const DEFAULT_STATE = {
  hb: "", rbc: "", wbc: "", platelets: "", mcv: "", age: "",
  bp: "", bmi: "", bgr: "", bu: "", sc: "", sod: "",
  pot: "", hemo: "", wc: "", bilirubin: "", alt: "",
  ast: "", hba1c: ""
};

const LABELS = {
  hb: "Hemoglobin", rbc: "Red Blood Cells", wbc: "White Blood Cells",
  platelets: "Platelets", mcv: "MCV", age: "Age (Years)",
  bp: "Blood Pressure", bmi: "BMI", bgr: "Blood Glucose Random",
  bu: "Blood Urea", sc: "Serum Creatinine", sod: "Sodium",
  pot: "Potassium", hemo: "Hemo (Variant)", wc: "White Cell Count",
  bilirubin: "Bilirubin", alt: "ALT (SGPT)", ast: "AST (SGOT)", hba1c: "HbA1c"
};

const BloodPrediction = () => {
  const [formData, setFormData] = useState(DEFAULT_STATE);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const payload = Object.keys(formData).reduce((acc, key) => {
        acc[key] = parseFloat(formData[key]) || 0;
        return acc;
      }, {});

      const res = await axios.post('http://127.0.0.1:8000/predict', payload);
      setResult(res.data);
    } catch (err) {
      console.error(err);
      setError("Failed to connect to the prediction server or an error occurred.");
    } finally {
      setLoading(false);
    }
  };

  const downloadResult = () => {
    if (!result) return;
    
    let content = "BLOOD ANALYSIS REPORT\n";
    content += "Date: " + new Date().toLocaleString() + "\n";
    content += "----------------------------------------\n";
    content += "PREDICTION: " + result.prediction + "\n";
    if (result.confidence) {
        content += "CONFIDENCE: " + (result.confidence * 100).toFixed(2) + "%\n";
    }
    content += "----------------------------------------\n";
    content += "INPUT PARAMETERS:\n";
    Object.keys(formData).forEach(key => {
        content += LABELS[key] + ": " + formData[key] + "\n";
    });
    content += "\n----------------------------------------\n";
    content += "Generated by Blood Analysis Intelligence";

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `blood-analysis-report-${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: '2rem 1.5rem', width: '100%', maxWidth: '1100px', margin: '0 auto', paddingBottom: '4rem' }} className="animate-fade-in">
      <div className="glass-panel" style={{ padding: '3.5rem' }}>

        <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '72px', height: '72px', borderRadius: '50%', background: 'rgba(59, 130, 246, 0.1)', color: 'var(--accent)', marginBottom: '1.5rem', border: '1px solid rgba(59, 130, 246, 0.2)' }}>
            <Droplet size={36} />
          </div>
          <h2 style={{ fontSize: '2.4rem', fontWeight: '700', marginBottom: '0.75rem', background: 'linear-gradient(to right, #ffffff, #94a3b8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', letterSpacing: '-0.02em' }}>
            Blood Analysis
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>Enter the vital statistics below for an AI-powered blood assessment.</p>
        </div>

        <form onSubmit={handleSubmit}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1.5rem', marginBottom: '3.5rem' }}>
            {Object.keys(DEFAULT_STATE).map((key) => (
              <div key={key}>
                <label className="input-label" htmlFor={key}>{LABELS[key] || key.toUpperCase()}</label>
                <input
                  type="number"
                  id={key}
                  name={key}
                  step="any"
                  className="input-field"
                  value={formData[key]}
                  onChange={handleChange}
                  placeholder={"0.0"}
                  required
                />
              </div>
            ))}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
            <button type="submit" className="btn-primary" disabled={loading} style={{ maxWidth: '300px' }}>
              {loading ? <Activity className="spinner" size={22} /> : <Droplet size={22} />}
              {loading ? 'Analyzing Data...' : 'Generate Prediction'}
            </button>

            {error && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--danger)', background: 'rgba(239, 68, 68, 0.08)', border: '1px solid rgba(239, 68, 68, 0.2)', padding: '1.25rem', borderRadius: '16px', width: '100%', maxWidth: '600px' }} className="animate-fade-in">
                <AlertCircle size={24} style={{ flexShrink: 0 }} />
                <p style={{ margin: 0, fontWeight: 500 }}>{error}</p>
              </div>
            )}

            {result !== null && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)', padding: '2.5rem', borderRadius: '24px', width: '100%', maxWidth: '600px', textAlign: 'center', marginTop: '1rem' }} className="animate-fade-in">
                <div style={{ color: 'var(--success)', marginBottom: '0.5rem' }}>
                  <CheckCircle2 size={48} />
                </div>
                <h3 style={{ fontSize: '1.3rem', color: 'var(--text-main)', margin: 0, fontWeight: 500 }}>Analysis Complete</h3>
                <p style={{ fontSize: '2.5rem', fontWeight: '700', color: 'var(--success)', margin: '0.5rem 0', letterSpacing: '-0.02em', textTransform: 'capitalize' }}>
                  {result.prediction || (typeof result === 'number' ? result.toFixed(4) : JSON.stringify(result))}
                </p>
                {result.confidence && (
                  <p style={{ color: 'var(--text-main)', fontSize: '1.1rem', margin: '0.5rem 0', fontWeight: 500 }}>
                    Confidence: {(result.confidence * 100).toFixed(2)}%
                  </p>
                )}
                
                <div style={{ width: '100%', borderTop: '1px solid rgba(255,255,255,0.1)', margin: '1rem 0' }}></div>
                
                <button 
                  type="button" 
                  onClick={downloadResult}
                  className="btn-secondary"
                  style={{ display: 'flex', alignItems: 'center', justifyItems: 'center', gap: '0.5rem' }}
                >
                  <Download size={18} /> Download Full Report
                </button>
              </div>
            )}
          </div>
        </form>

      </div>
    </div>
  );
};

export default BloodPrediction;
