import React, { useState } from 'react';
import { Activity, AlertCircle, CheckCircle2, Download, UploadCloud, FileImage } from 'lucide-react';

const BoneBreakage = () => {
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file && file.type.startsWith('image/')) {
      setSelectedFile(file);
      setError(null);
      
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
      setResult(null);
    } else {
      setError("Please select a valid image file (JPEG, PNG).");
      setSelectedFile(null);
      setPreview(null);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (file && file.type.startsWith('image/')) {
      setSelectedFile(file);
      setError(null);
      
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
      setResult(null);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!selectedFile) {
        setError("Please upload an X-ray image first.");
        return;
    }
    setLoading(true);
    setError(null);
    setResult(null);

    // Mock prediction logic for Bone Breakage Analysis
    setTimeout(() => {
      try {
        const isFractured = Math.random() > 0.5;
        setResult({
          prediction: isFractured ? "Fracture Detected" : "Normal Bone Structure",
          confidence: Math.random() * 0.2 + 0.8
        });
      } catch (err) {
        setError("Failed to analyze the image.");
      } finally {
        setLoading(false);
      }
    }, 2000);
  };

  const downloadResult = () => {
    if (!result) return;
    
    let content = "BONE FRACTURE ANALYSIS REPORT\n";
    content += "Date: " + new Date().toLocaleString() + "\n";
    content += "----------------------------------------\n";
    content += "PREDICTION: " + result.prediction + "\n";
    if (result.confidence) {
        content += "CONFIDENCE: " + (result.confidence * 100).toFixed(2) + "%\n";
    }
    content += "----------------------------------------\n";
    content += "FILE ANALYZED: " + (selectedFile?.name || "Unknown") + "\n";
    content += "\n----------------------------------------\n";
    content += "Generated by Health Intelligence";

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bone-analysis-report-${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: '2rem 1.5rem', width: '100%', maxWidth: '1100px', margin: '0 auto', paddingBottom: '4rem' }} className="animate-fade-in">
      <div className="glass-panel" style={{ padding: '3.5rem' }}>

        <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '72px', height: '72px', borderRadius: '50%', background: 'rgba(234, 179, 8, 0.1)', color: '#eab308', marginBottom: '1.5rem', border: '1px solid rgba(234, 179, 8, 0.2)' }}>
            <Activity size={36} />
          </div>
          <h2 style={{ fontSize: '2.4rem', fontWeight: '700', marginBottom: '0.75rem', background: 'linear-gradient(to right, #ffffff, #94a3b8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', letterSpacing: '-0.02em' }}>
            Bone Breakage Analysis
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>Upload a bone X-ray image for instant AI fracture detection.</p>
        </div>

        <form onSubmit={handleSubmit}>
          <div 
            style={{ 
                border: '2px dashed rgba(255,255,255,0.2)', 
                borderRadius: '24px', 
                padding: '4rem 2rem', 
                textAlign: 'center',
                marginBottom: '2.5rem',
                background: preview ? 'rgba(0,0,0,0.2)' : 'rgba(255,255,255,0.02)',
                position: 'relative',
                transition: 'all 0.3s ease'
            }}
            onDragOver={(e) => e.preventDefault()}
            onDrop={handleDrop}
          >
            <input 
              type="file" 
              accept="image/*" 
              onChange={handleFileChange}
              style={{
                  position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', 
                  opacity: 0, cursor: 'pointer'
              }}
            />
            {preview ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                    <img src={preview} alt="X-ray preview" style={{ maxHeight: '300px', borderRadius: '12px', marginBottom: '1.5rem', border: '1px solid rgba(255,255,255,0.1)' }} />
                    <p style={{ color: 'var(--text-main)', fontWeight: 500 }}>{selectedFile?.name}</p>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginTop: '0.5rem' }}>Click or drag a new image to replace</p>
                </div>
            ) : (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', color: 'var(--text-muted)' }}>
                    <UploadCloud size={48} style={{ marginBottom: '1rem', color: '#eab308' }} />
                    <h3 style={{ color: 'var(--text-main)', fontSize: '1.25rem', marginBottom: '0.5rem' }}>Drag & Drop your X-ray here</h3>
                    <p>or click to browse from your computer (JPEG, PNG)</p>
                </div>
            )}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
            <button type="submit" className="btn-primary" disabled={loading || !selectedFile} style={{ maxWidth: '300px', background: 'linear-gradient(135deg, #ca8a04, #eab308)' }}>
              {loading ? <Activity className="spinner" size={22} /> : <FileImage size={22} />}
              {loading ? 'Analyzing Image...' : 'Analyze X-Ray'}
            </button>

            {error && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--danger)', background: 'rgba(239, 68, 68, 0.08)', border: '1px solid rgba(239, 68, 68, 0.2)', padding: '1.25rem', borderRadius: '16px', width: '100%', maxWidth: '600px' }} className="animate-fade-in">
                <AlertCircle size={24} style={{ flexShrink: 0 }} />
                <p style={{ margin: 0, fontWeight: 500 }}>{error}</p>
              </div>
            )}

            {result !== null && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)', padding: '2.5rem', borderRadius: '24px', width: '100%', maxWidth: '600px', textAlign: 'center', marginTop: '1rem' }} className="animate-fade-in">
                <div style={{ color: result.prediction.includes('Fracture') ? 'var(--danger)' : 'var(--success)', marginBottom: '0.5rem' }}>
                  {result.prediction.includes('Fracture') ? <AlertCircle size={48} /> : <CheckCircle2 size={48} />}
                </div>
                <h3 style={{ fontSize: '1.3rem', color: 'var(--text-main)', margin: 0, fontWeight: 500 }}>Analysis Complete</h3>
                <p style={{ fontSize: '2.5rem', fontWeight: '700', color: result.prediction.includes('Fracture') ? 'var(--danger)' : 'var(--success)', margin: '0.5rem 0', letterSpacing: '-0.02em', textTransform: 'capitalize' }}>
                  {result.prediction}
                </p>
                {result.confidence && (
                  <p style={{ color: 'var(--text-main)', fontSize: '1.1rem', margin: '0.5rem 0', fontWeight: 500 }}>
                    Confidence: {(result.confidence * 100).toFixed(2)}%
                  </p>
                )}
                
                <div style={{ width: '100%', borderTop: '1px solid rgba(255,255,255,0.1)', margin: '1rem 0' }}></div>
                
                <button 
                  type="button" 
                  onClick={downloadResult}
                  className="btn-secondary"
                  style={{ display: 'flex', alignItems: 'center', justifyItems: 'center', gap: '0.5rem' }}
                >
                  <Download size={18} /> Download Full Report
                </button>
              </div>
            )}
          </div>
        </form>

      </div>
    </div>
  );
};

export default BoneBreakage;
