import React, { useState } from 'react';
import { Activity, AlertCircle, Heart, CheckCircle2, Download } from 'lucide-react';

const DEFAULT_STATE = {
  age: "", sex: "", cp: "", trestbps: "", chol: "", fbs: "",
  restecg: "", thalach: "", exang: "", oldpeak: "", slope: "",
  ca: "", thal: ""
};

const LABELS = {
  age: "Age", sex: "Sex (1=M, 0=F)", cp: "Chest Pain Type", 
  trestbps: "Resting Blood Pressure", chol: "Serum Cholestoral", 
  fbs: "Fasting Blood Sugar", restecg: "Resting ECG Results", 
  thalach: "Max Heart Rate", exang: "Exercise Induced Angina", 
  oldpeak: "ST Depression", slope: "Slope of Peak ST",
  ca: "Num Major Vessels", thal: "Thal (3=norm, 6=fixed, 7=revers)"
};

const HeartPrediction = () => {
  const [formData, setFormData] = useState(DEFAULT_STATE);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);

    // Mock prediction logic since we don't have the backend endpoint yet for heart
    setTimeout(() => {
      try {
        setResult({
          prediction: Math.random() > 0.5 ? "High Risk" : "Low Risk",
          confidence: Math.random() * 0.4 + 0.6
        });
      } catch (err) {
        setError("Failed to generate prediction.");
      } finally {
        setLoading(false);
      }
    }, 1500);
  };

  const downloadResult = () => {
    if (!result) return;
    
    let content = "HEART ANALYSIS REPORT\n";
    content += "Date: " + new Date().toLocaleString() + "\n";
    content += "----------------------------------------\n";
    content += "PREDICTION: " + result.prediction + "\n";
    if (result.confidence) {
        content += "CONFIDENCE: " + (result.confidence * 100).toFixed(2) + "%\n";
    }
    content += "----------------------------------------\n";
    content += "INPUT PARAMETERS:\n";
    Object.keys(formData).forEach(key => {
        content += LABELS[key] + ": " + formData[key] + "\n";
    });
    content += "\n----------------------------------------\n";
    content += "Generated by Health Intelligence";

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `heart-analysis-report-${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: '2rem 1.5rem', width: '100%', maxWidth: '1100px', margin: '0 auto', paddingBottom: '4rem' }} className="animate-fade-in">
      <div className="glass-panel" style={{ padding: '3.5rem' }}>

        <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '72px', height: '72px', borderRadius: '50%', background: 'rgba(239, 68, 68, 0.1)', color: 'var(--danger)', marginBottom: '1.5rem', border: '1px solid rgba(239, 68, 68, 0.2)' }}>
            <Heart size={36} />
          </div>
          <h2 style={{ fontSize: '2.4rem', fontWeight: '700', marginBottom: '0.75rem', background: 'linear-gradient(to right, #ffffff, #94a3b8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', letterSpacing: '-0.02em' }}>
            Heart Disease Prediction
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>Enter the clinical parameters below for an AI-powered heart health assessment.</p>
        </div>

        <form onSubmit={handleSubmit}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1.5rem', marginBottom: '3.5rem' }}>
            {Object.keys(DEFAULT_STATE).map((key) => (
              <div key={key}>
                <label className="input-label" htmlFor={key}>{LABELS[key] || key.toUpperCase()}</label>
                <input
                  type="number"
                  id={key}
                  name={key}
                  step="any"
                  className="input-field"
                  value={formData[key]}
                  onChange={handleChange}
                  placeholder={"0"}
                  required
                />
              </div>
            ))}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
            <button type="submit" className="btn-primary" disabled={loading} style={{ maxWidth: '300px', background: 'linear-gradient(135deg, #ef4444, #f43f5e)' }}>
              {loading ? <Activity className="spinner" size={22} /> : <Heart size={22} />}
              {loading ? 'Analyzing Data...' : 'Generate Prediction'}
            </button>

            {error && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--danger)', background: 'rgba(239, 68, 68, 0.08)', border: '1px solid rgba(239, 68, 68, 0.2)', padding: '1.25rem', borderRadius: '16px', width: '100%', maxWidth: '600px' }} className="animate-fade-in">
                <AlertCircle size={24} style={{ flexShrink: 0 }} />
                <p style={{ margin: 0, fontWeight: 500 }}>{error}</p>
              </div>
            )}

            {result !== null && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)', padding: '2.5rem', borderRadius: '24px', width: '100%', maxWidth: '600px', textAlign: 'center', marginTop: '1rem' }} className="animate-fade-in">
                <div style={{ color: result.prediction === 'High Risk' ? 'var(--danger)' : 'var(--success)', marginBottom: '0.5rem' }}>
                  {result.prediction === 'High Risk' ? <AlertCircle size={48} /> : <CheckCircle2 size={48} />}
                </div>
                <h3 style={{ fontSize: '1.3rem', color: 'var(--text-main)', margin: 0, fontWeight: 500 }}>Analysis Complete</h3>
                <p style={{ fontSize: '2.5rem', fontWeight: '700', color: result.prediction === 'High Risk' ? 'var(--danger)' : 'var(--success)', margin: '0.5rem 0', letterSpacing: '-0.02em', textTransform: 'capitalize' }}>
                  {result.prediction}
                </p>
                {result.confidence && (
                  <p style={{ color: 'var(--text-main)', fontSize: '1.1rem', margin: '0.5rem 0', fontWeight: 500 }}>
                    Confidence: {(result.confidence * 100).toFixed(2)}%
                  </p>
                )}
                
                <div style={{ width: '100%', borderTop: '1px solid rgba(255,255,255,0.1)', margin: '1rem 0' }}></div>
                
                <button 
                  type="button" 
                  onClick={downloadResult}
                  className="btn-secondary"
                  style={{ display: 'flex', alignItems: 'center', justifyItems: 'center', gap: '0.5rem' }}
                >
                  <Download size={18} /> Download Full Report
                </button>
              </div>
            )}
          </div>
        </form>

      </div>
    </div>
  );
};

export default HeartPrediction;
